- name: Deploy BentoML securely using Docker Compose
  hosts: bentoml-host
  become: yes
  vars:
    bentoml_port: 3000
  tasks:
    - name: Ensure docker-compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Create BentoML directory
      file:
        path: /opt/bentoml
        state: directory
        mode: '0750'

    - name: Create docker-compose.yml for BentoML
      copy:
        dest: /opt/bentoml/docker-compose.yml
        content: |
          version: "3.7"
          services:
            bentoml:
              image: bentoml/bentoml:latest
              container_name: bentoml
              ports:
                - "{{ bentoml_port }}:3000"
              volumes:
                - bentoml_data:/bentoml
              environment:
                BENTOML_HOME: /bentoml
              restart: unless-stopped
          volumes:
            bentoml_data:

    - name: Start BentoML service via docker-compose
      docker_compose:
        project_src: /opt/bentoml
        state: present
        restarted: yes
